# Generated by Django 4.2.11 on 2026-04-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_fields', models.JSONField(default=list)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_logs', to='lms.course')),
            ],
            options={
                'verbose_name': 'Лог обновления курса',
                'verbose_name_plural': 'Логи обновлений курсов',
                'ordering': ['-updated_at'],
            },
        ),
    ]
